### ISSUE TITLE
Pingdom icon links to Google

### ISSUE THREAD

**Issue by conconnl** [pe7er/db8optimize#2]
https://github.com/pe7er/db8optimize/blob/master/source/administrator/components/com_db8optimize/views/performance/tmpl/default.php

https://github.com/pe7er/db8optimize/blob/master/source/administrator/components/com_db8optimize/views/mobile/tmpl/default.php

**Comment by pe7er** [comment]
Thanks!
I've changed the link to pingdom, but it does not accept the website to test via URL.
I'll remove this option.
